/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/addadresses`; params?: Router.UnknownInputParams; } | { pathname: `/Adminreport`; params?: Router.UnknownInputParams; } | { pathname: `/adresses`; params?: Router.UnknownInputParams; } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/chart`; params?: Router.UnknownInputParams; } | { pathname: `/finishorder`; params?: Router.UnknownInputParams; } | { pathname: `/finishreport`; params?: Router.UnknownInputParams; } | { pathname: `/food`; params?: Router.UnknownInputParams; } | { pathname: `/history`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/mystery`; params?: Router.UnknownInputParams; } | { pathname: `/ordersum`; params?: Router.UnknownInputParams; } | { pathname: `/otpverify`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/report`; params?: Router.UnknownInputParams; } | { pathname: `/seller`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/Toastprovider`; params?: Router.UnknownInputParams; } | { pathname: `/forgotpassword`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/addadresses`; params?: Router.UnknownOutputParams; } | { pathname: `/Adminreport`; params?: Router.UnknownOutputParams; } | { pathname: `/adresses`; params?: Router.UnknownOutputParams; } | { pathname: `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/chart`; params?: Router.UnknownOutputParams; } | { pathname: `/finishorder`; params?: Router.UnknownOutputParams; } | { pathname: `/finishreport`; params?: Router.UnknownOutputParams; } | { pathname: `/food`; params?: Router.UnknownOutputParams; } | { pathname: `/history`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/mystery`; params?: Router.UnknownOutputParams; } | { pathname: `/ordersum`; params?: Router.UnknownOutputParams; } | { pathname: `/otpverify`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/report`; params?: Router.UnknownOutputParams; } | { pathname: `/seller`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/Toastprovider`; params?: Router.UnknownOutputParams; } | { pathname: `/forgotpassword`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/addadresses${`?${string}` | `#${string}` | ''}` | `/Adminreport${`?${string}` | `#${string}` | ''}` | `/adresses${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `/chart${`?${string}` | `#${string}` | ''}` | `/finishorder${`?${string}` | `#${string}` | ''}` | `/finishreport${`?${string}` | `#${string}` | ''}` | `/food${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/mystery${`?${string}` | `#${string}` | ''}` | `/ordersum${`?${string}` | `#${string}` | ''}` | `/otpverify${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/report${`?${string}` | `#${string}` | ''}` | `/seller${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/Toastprovider${`?${string}` | `#${string}` | ''}` | `/forgotpassword${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/addadresses`; params?: Router.UnknownInputParams; } | { pathname: `/Adminreport`; params?: Router.UnknownInputParams; } | { pathname: `/adresses`; params?: Router.UnknownInputParams; } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/chart`; params?: Router.UnknownInputParams; } | { pathname: `/finishorder`; params?: Router.UnknownInputParams; } | { pathname: `/finishreport`; params?: Router.UnknownInputParams; } | { pathname: `/food`; params?: Router.UnknownInputParams; } | { pathname: `/history`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/mystery`; params?: Router.UnknownInputParams; } | { pathname: `/ordersum`; params?: Router.UnknownInputParams; } | { pathname: `/otpverify`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/report`; params?: Router.UnknownInputParams; } | { pathname: `/seller`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/Toastprovider`; params?: Router.UnknownInputParams; } | { pathname: `/forgotpassword`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
